version: '3.8'

services:
  backend:
    image: lukaszlosieczka/tictactoe-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database-1.cpe6cau4cqwa.us-east-1.rds.amazonaws.com:3306/mydatabase?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root1234
      ALLOWED_ORIGIN: http://tictactoe-env.eba-p3vemxbk.us-east-1.elasticbeanstalk.com
  frontend:
    image: lukaszlosieczka/tictactoe-frontend
    ports:
      - "80:80"